---
# defaults
host: http://192.168.1.101:81
proxy_host:
  - domain_names: ["truenas.nodadyoushutup.com"]
    forward_scheme: "http"
    forward_host: "192.168.1.100"
    forward_port: 80
    ssl_forced: true
    hsts_enabled: true
    hsts_subdomains: true
    http2_support: true
    block_exploits: true
    caching_enabled: false
    allow_websocket_upgrade: true
    access_list_id: 0
    enabled: true
  - domain_names: ["overseerr.nodadyoushutup.com"]
    forward_scheme: "http"
    forward_host: "192.168.1.101"
    forward_port: 9055
    ssl_forced: true
    hsts_enabled: true
    hsts_subdomains: true
    http2_support: true
    block_exploits: true
    caching_enabled: false
    allow_websocket_upgrade: true
    access_list_id: 0
    enabled: true