---
- name: Copy nginx_proxy_manager_auth.sh to the ansible user's home
  template:
    src: nginx_proxy_manager_auth.sh.j2
    dest: /home/{{ ansible_user }}/nginx_proxy_manager_auth.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
