---
- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
    
- name: Run docker compose down
  shell: |
    export COMPOSE_FILE=/home/{{ ansible_user }}/docker-compose.yaml
    docker compose down
  args:
    executable: /bin/bash
  environment:
    COMPOSE_FILE: /home/{{ ansible_user }}/docker-compose.yaml