---
- name: Load variables and debug
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Include YAML variables from local file
      include_vars:
        file: "{{ playbook_dir }}/config.sub.yaml"
        name: config

    - name: Print the loaded variables
      debug:
        var: config.default
