---
- name: APT lock check
  include_role:
    name: ../../role/apt_lock_check

- name: Uninstall unwanted packages 
  apt: 
    name: 
      - docker.io 
      - docker-compose 
      - docker-compose-v2 
      - docker-doc 
      - podman-docker 
    state: absent 
    lock_timeout: 120
  when: apt_lock_check_success

- name: Create the /etc/apt/keyrings directory with 0755 permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key using curl
  command:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"

- name: Set read permission for all users on the Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set up Docker APT repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Update packages
  apt: 
    update_cache: yes

- name: APT lock check
  include_role:
    name: ../../role/apt_lock_check

- name: Install Docker
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin 
    state: present 
    update_cache: yes
    lock_timeout: 120
  when: apt_lock_check_success

- name: Ensure group "docker" exists with correct gid
  group:
    name: docker
    state: present
    
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Restart session to apply group changes
  shell: newgrp docker

- name: Copy docker-compose.yaml to the ansible user's home
  copy:
    src: "{{ lookup('env', 'COMPOSE_FILE') }}"
    dest: /home/{{ ansible_user }}/docker-compose.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy docker.env to the ansible user's home
  copy:
    src: /mnt/workspace/.env
    dest: /home/{{ ansible_user }}/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

