---
########################################
default:
  ip_address: &ip_address ${TF_VAR_DEFAULT_IP_ADDRESS}
  password: &password ${TF_VAR_DEFAULT_PASSWORD}
  private_key: &private_key ${TF_VAR_DEFAULT_PRIVATE_KEY}
  public_key_dir: &public_key_dir ${TF_VAR_DEFAULT_PUBLIC_KEY_DIR}
########################################
proxmox:
  auth:
    password: *password
    realm: pve
    username: root
  datastore_id: virtualization
  endpoint: 
    ip_address: *ip_address
    port: 1086
    protocol: "https"
    insecure: true
  random_vm:
    enabled: true
    start: 120
    end: 199
  ssh:
    agent:
      enabled: true
      socket: 1022
    private_key: *private_key
    node:
      name: pve
      address: *ip_address
      port: 1022
talos:
  cluster_name: "talos-proxmox"
  control_plane:
    - ip_address: *ip_address
      port: 1200
    - ip_address: *ip_address
      port: 1201
    - ip_address: *ip_address
      port: 1202
  worker:
    - ip_address: *ip_address
      port: 1203
    - ip_address: *ip_address
      port: 1204
    - ip_address: *ip_address
      port: 1205
    - ip_address: *ip_address
      port: 1206