---
- name: Verify MySQL connectivity
  command: "mysqladmin ping -h 192.168.1.101 -u npm -pnpm"
  register: mysql_connectivity
  retries: 5
  delay: 10
  until: mysql_connectivity.rc == 0
  failed_when: mysql_connectivity.rc != 0

- name: Ensure MySQL is connectable
  debug:
    msg: "MySQL is connectable."
  when: mysql_connectivity.rc == 0

- name: Check if 'user' table exists
  command: "mysql -h 192.168.1.101 -u npm -pnpm -D npm -e \"SHOW TABLES LIKE 'user';\""
  register: user_table_check
  retries: 5
  delay: 10
  until: user_table_check.stdout.find("user") != -1

- name: Ensure 'user' table exists
  assert:
    that:
      - user_table_check.stdout.find("user") != -1
    fail_msg: "The 'user' table does not exist in the MySQL database."

- name: Check if 'auth' table exists
  command: "mysql -h 192.168.1.101 -u npm -pnpm -D npm -e \"SHOW TABLES LIKE 'auth';\""
  register: auth_table_check
  retries: 5
  delay: 10
  until: auth_table_check.stdout.find("auth") != -1

- name: Ensure 'auth' table exists
  assert:
    that:
      - auth_table_check.stdout.find("auth") != -1
    fail_msg: "The 'auth' table does not exist in the MySQL database."
