---
- name: Get token
  uri:
    url: "http://192.168.1.101:81/api/tokens"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      identity: "admin@nodadyoushutup.com"
      secret: "password"
    return_content: yes
  register: token_response

- name: Extract token
  set_fact:
    token: "{{ token_response.json.token }}"
  when: token_response.json.token is defined

- name: Fail if token retrieval failed
  fail:
    msg: "Failed to retrieve token."
  when: token is not defined

- name: Check if SSL certificate exists for domain
  uri:
    url: "http://{{ host_config.forward_host }}:{{ host_config.forward_port }}/api/nginx/certificates"
    method: GET
    headers:
      Authorization: "Bearer {{ token }}"
    return_content: yes
  register: certificates_response
  with_items: "{{ proxy_host }}"
  loop_control:
    loop_var: host_config

- name: Find existing certificate ID
  set_fact:
    certificate_id: "{{ item.json.id }}"
  when: item.json.domain_names == host_config.domain_names
  loop: "{{ certificates_response.results }}"
  loop_control:
    loop_var: item
