---
dependency_deploy:
  docker:
    infra: true
    init: true
path:
  private_key: /mnt/workspace/id_rsa
  cloud_config: /mnt/workspace/cloud_config.yaml
  inventory: /mnt/workspace/inventory
  env: /mnt/workspace/.env
  gitconfig: /mnt/workspace/source/config/.gitconfig
  ansible: /mnt/workspace/source/config/ansible.cfg
  docker_compose: /mnt/workspace/source/config/docker-compose.yaml
  prometheus: /mnt/workspace/source/config/prometheus.yaml
provider:
  proxmox:
    endpoint:
    insecure:
    username:
    password:
    ssh:
      private_key:
      node:
        address:
        name:
        port:
  fortigate:
    hostname:
    insecure:
    username:
    password:
  postgres:
    host:
    port:
    database:
    username:
    password:
    sslmode:
    connect_timeout:
    clientcert:
      cert:
      key:
virtual_machine:
  datastore_id:
    iso: local
    cloud_config: local
    disk: local-lvm
  file_id: jammy-server-cloudimg-amd64.img
  keys: []
  bridge: "vmbr0"
  docker:
    vm_id: 101
    tags: ["terraform", "ubuntu", "docker"]
    startup:
      order: 1
      up_delay: 0
      down_delay: 0
    cpu:
      cores: 4
      type: "x86-64-v2-AES"
    disk:
      datastore_id: 
      file_id: 
      interface: "scsi0"
      size: 100
    address: 192.168.1.101/24
    gateway: "192.168.1.1"
    memory: 4096
    