# roles/host_add_from_config/tasks/main.yaml
- name: Add host from config
  host_add:
    name: "{{ config.virtual_machine[key].ansible.host }}:{{ config.virtual_machine[key].ansible.port }}"
    ansible_host: "{{ config.virtual_machine[key].ansible.host }}"
    ansible_port: "{{ config.virtual_machine[key].ansible.port }}"
    groups: "{{ key }}"
  delegate_to: localhost
  run_once: true
