---
- name: Load configuration
  include_vars:
    file: "{{ lookup('env', 'TF_VAR_CONFIG') }}"
    name: config
  delegate_to: localhost
  run_once: true

- name: Set config as a fact
  set_fact:
    config: "{{ config }}"
  delegate_to: localhost
  run_once: true

- name: Show config
  debug:
    var: config

- name: Show config structure
  debug:
    var: config.virtual_machine