---
- name: Copy prometheus config to the ansible user's home
  copy:
    src: "{{ config.path.prometheus }}"
    dest: /home/{{ ansible_user }}/prometheus.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'