---
# docker_init.
- name: Initialize Docker Environment
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Verify Ping Status
      include_role:
        name: ../role/vm_ping

    - name: Docker Setup and Service Management
      block:
        - name: VM Initialization Tasks
          include_role:
            name: ../role/vm_init

        - name: Install or Update Docker
          include_role:
            name: ../role/docker_install

        - name: Restart Docker Compose Managed Services
          include_role:
            name: ../role/docker_compose
          vars:
            run_down: true
            run_up: true
            up_services: ""
            down_services: ""
      when: vm_ping == true
