---
# docker_init.
- name: Initialize Docker Environment
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Ping VM
      include_role:
        name: ../role/vm_ping

    - name: Load configuration
      include_vars:
        file: "{{ lookup('env', 'TF_VAR_CONFIG') }}"
        name: config
      delegate_to: localhost
      run_once: true

    - name: Docker Setup and Service Management
      block:
        - name: VM Initialization Tasks
          include_role:
            name: ../role/vm_init

    #     # This will turn into a overall migrate config role
    #     # to run all configuration migrations
    #     - name: Migrate Prometheus configuration
    #       include_role:
    #         name: ../role/prometheus_config

    #     - name: Install or Update Docker
    #       include_role:
    #         name: ../role/docker_install
    #   when: vm_ping == true
