---
# npm.
- name: Add Docker Hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../role/config_load

    - name: Add Host from Config
      include_role:
        name: ../role/host_add
      vars:
        key: docker

- name: Initialize Nginx Proxy Manager
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../role/config_load

    - name: Ping VM
      include_role:
        name: ../role/vm_ping

    - name: Initialize Nginx Proxy Manager
      block:
        # - name: Restart Docker Compose Managed Services
        #   include_role:
        #     name: ../role/docker_compose
        #   vars:
        #     run_down: true
        #     run_up: true
        #     up_services: "mysql nginx-proxy-manager"
        #     down_services: "mysql nginx-proxy-manager"

        - name: Set NPM Administrator Password
          include_role:
            name: ../role/nginx_proxy_manager_admin

        - name: Set NPM Certificates and Hosts
          include_role:
            name: ../role/nginx_proxy_manager_host
      when: vm_ping == true
