---
# docker_init
- name: Add Docker Hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../../role/config_load

    - name: Add Host from Config
      include_role:
        name: ../../role/host_add
      vars:
        key: docker

- name: Initialize Docker Environment
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../../role/config_load

    - name: Ping VM
      include_role:
        name: ../../role/virtual_machine/ping

    - name: Docker Setup and Service Management
      block:
        - name: VM Initialization Tasks
          include_role:
            name: ../../role/virtual_machine/init

        - name: Migrate Prometheus configuration
          include_role:
            name: ../../role/prometheus

        - name: Migrate Nginx Proxy Manager auth fix script
          include_role:
            name: ../../role/nginx_proxy_manager_auth

        - name: Install or Update Docker
          include_role:
            name: ../../role/docker/install
      when: virtual_machine/ping == true
