---
- name: Initialize Docker Environment
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Verify APT Lock Status
      include_role:
        name: ../../role/vm_ping

    - name: Docker Setup and Service Management
      block:
        - name: Execute VM Initialization Tasks
          include_role:
            name: ../../role/vm_init

        - name: Install or Update Docker
          include_role:
            name: ../../role/docker_install

        - name: Stop Docker-Compose Managed Services
          include_role:
            name: ../../role/docker_compose_down

        - name: Start Docker-Compose Managed Services
          include_role:
            name: ../../role/docker_compose_up
      when: ssh_check_success == true
