---
- name: Add user to sudo group
  user:
    name: "{{ ansible_user }}"
    groups: "sudo"
    append: yes

- name: Copy .gitconfig
  include_role:
    name: ../../role/gitconfig

- name: APT lock check
  include_role:
    name: ../../role/virtual_machine/apt_lock_check

- block:
  - name: Install necessary packages
    apt:
      name:
        - nfs-common
        - zip
        - net-tools
        - ca-certificates
        - curl
        - postgresql-client
        - mysql-client-core-8.0
        - git
        - python3
        - python3-pip
        - whois
        - jq
      state: present
      update_cache: yes
      # more later
  when: apt_lock_check_success
  name: "Add user and install packages only after apt lock is cleared"

- name: Node exporter
  include_role:
    name: ../../role/node_exporter

