services:
  jenkins:
    image: ghcr.io/nodadyoushutup/jenkins-controller:latest
    container_name: jenkins-controller
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      JENKINS_SECURITY_ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      JENKINS_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}
      CASC_JENKINS_CONFIG: "/var/jenkins_home/jenkins.yaml"
      SECRETS_DIR: "/var/jenkins_home/.jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - compose_jenkins_controller:/var/jenkins_home
      - nfs_jenkins:/var/jenkins_home/.jenkins
      - nfs_ssh:/var/jenkins_home/.ssh
      - nfs_kube:/var/jenkins_home/.kube
      - nfs_tfvars:/var/jenkins_home/.tfvars
      - /dev/kvm:/dev/kvm
    configs:
      - source: casc_config
        target: /var/jenkins_home/jenkins.yaml
    dns:
      - 1.1.1.1
      - 1.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/whoAmI/api/json?tree=authenticated"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 1m

volumes:
  compose_jenkins_controller:
  nfs_jenkins:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,nolock,hard,rw
      device: ":/mnt/eapp/skel/.jenkins"
  nfs_ssh:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,nolock,hard,rw
      device: ":/mnt/eapp/skel/.ssh"
  nfs_kube:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,nolock,hard,rw
      device: ":/mnt/eapp/skel/.kube"
  nfs_tfvars:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,nolock,hard,rw
      device: ":/mnt/eapp/skel/.tfvars"

configs:
  casc_config:
    file: ./config.yaml
