---
- name: Check if SSH port is reachable on the target host using nc (netcat)
  command: nc -zv {{ ansible_host }} {{ ansible_port }}
  register: nc_result
  retries: 18
  delay: 10
  until: nc_result.rc == 0
  ignore_errors: true
  tags: check_ssh

- name: Set SSH check result as a fact
  set_fact:
    ssh_check_success: "{{ nc_result.rc == 0 }}"
