---
- name: Copy fstab to the remote machine
  template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'

- name: Create destination directories
  file:
    path: "{{ item.dest }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop: "{{ config.virtual_machine.fstab }}"

- name: Mount all filesystems in /etc/fstab
  command: mount -a