---
- name: Copy docker-compose.yaml to the ansible user's home
  copy:
    src: "{{ config.docker.compose }}"
    dest: /home/{{ ansible_user }}/docker-compose.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    
- name: Copy docker.env to the ansible user's home
  template:
    src: .env.j2
    dest: /home/{{ ansible_user }}/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    
- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Run docker compose down
  ansible.builtin.shell: |
    export COMPOSE_FILE=/home/{{ ansible_user }}/docker-compose.yaml
    docker compose down {{ down_services | default('') }}
  args:
    executable: /bin/bash
  environment:
    COMPOSE_FILE: "/home/{{ ansible_user }}/docker-compose.yaml"
  when: run_down

- name: Run docker compose up
  ansible.builtin.shell: |
    export COMPOSE_FILE=/home/{{ ansible_user }}/docker-compose.yaml
    docker compose up -d {{ up_services | default('') }} --remove-orphans
  args:
    executable: /bin/bash
  environment:
    COMPOSE_FILE: "/home/{{ ansible_user }}/docker-compose.yaml"
  when: run_up
