{
 "title": "Exportarr",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},instance)"
    }
   },
   {
    "name": "sabnzbd_instance",
    "label": "SABnzbd Instance",
    "query": {
     "query": "label_values({__name__=~\"sabnzbd_.*\"},instance)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},instance)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},instance)"
    }
   },
   {
    "name": "lidarr_instance",
    "label": "Lidarr Instance",
    "query": {
     "query": "label_values({__name__=~\"lidarr_.*\"},instance)"
    }
   },
   {
    "name": "readarr_instance",
    "label": "Readarr Instance",
    "query": {
     "query": "label_values({__name__=~\"readarr_.*\"},instance)"
    }
   },
   {
    "name": "bazarr_instance",
    "label": "Bazarr Instance",
    "query": {
     "query": "label_values({__name__=~\"bazarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Radarr - ${radarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "radarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_system_status{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "radarr_movie_monitored_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Monitored"
      },
      {
       "expr": "radarr_movie_wanted_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Wanted"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_queue_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "radarr_history_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Disk Used"
      }
     ]
    },
    {
     "title": "Qualities",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 485 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_movie_quality_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "{{quality}}"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 495 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 495 },
     "targets": [
      {
       "expr": "radarr_system_health_issues{instance=~\"${radarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sonarr - ${sonarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "sonarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1842 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_system_status{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_queue_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "sonarr_history_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "sonarr_episode_downloaded_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Downloaded"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_series_monitored_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Series Monitored"
      },
      {
       "expr": "max(sonarr_series_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Series Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_season_monitored_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Seasons Monitored"
      },
      {
       "expr": "max(sonarr_season_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Seasons Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1842 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_episode_missing_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Episodes Missing"
      },
      {
       "expr": "max(sonarr_episode_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Episodes Total"
      }
     ]
    },
    {
     "title": "Qualities",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1846 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_episode_quality_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "{{quality}}"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1856 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1856 },
     "targets": [
      {
       "expr": "sonarr_system_health_issues{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Lidarr - ${lidarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "lidarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3227 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_system_status{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "Songs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 3, "y": 3227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_queue_total{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "lidarr_songs_downloaded_total{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "lidarr_songs_total - lidarr_songs_downloaded_total",
       "legendFormat": "Missing"
      },
      { "expr": "lidarr_songs_total", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Artists",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 3227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(lidarr_artists_monitored_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(lidarr_artists_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Albums",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 3227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(lidarr_albums_monitored_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(lidarr_albums_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "max(lidarr_albums_missing_total{instance=~\"${lidarr_instance}\"})",
       "legendFormat": "Missing"
      }
     ]
    },
    {
     "title": "Song Qualities",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3260 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lidarr_songs_quality_total{instance=~\"${lidarr_instance}\"}\r\n",
       "legendFormat": "{{quality}}"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3270 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lidarr_artists_filesize_bytes{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 17, "x": 7, "y": 3270 },
     "targets": [
      {
       "expr": "lidarr_system_health_issues{instance=~\"${lidarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prowlarr - ${prowlarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "prowlarr_instance"
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{instance=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"}) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(user_agent) (prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bazarr - ${bazarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "bazarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"sabnzbd\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_status{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "Mode"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_time_estimate_seconds{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "Time Remaining"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_speed_bps{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "D/L Speed"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_pause_duration_seconds{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "Resume In"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16522 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(sabnzbd_disk_used_bytes{instance=~\"${sabnzbd_instance}\",folder=\"download\"} / sabnzbd_disk_total_bytes{instance=~\"${sabnzbd_instance}\",folder=\"download\"})",
       "legendFormat": "Download"
      },
      {
       "expr": "min(sabnzbd_disk_used_bytes{instance=~\"${sabnzbd_instance}\",folder=\"complete\"} / sabnzbd_disk_total_bytes{instance=~\"${sabnzbd_instance}\",folder=\"complete\"})",
       "legendFormat": "Complete"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16526 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bazarr_system_status{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16526 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bazarr_episode_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Episodes"
      },
      {
       "expr": "bazarr_movie_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Movies"
      },
      {
       "expr": "bazarr_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16526 },
     "targets": [
      {
       "expr": "bazarr_system_health_issues{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 16535 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"bazarr\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 15, "y": 16535 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_paused_all{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "Hard Pause"
      }
     ]
    },
    {
     "title": "Download Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16539 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(rate(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16539 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval]))",
       "legendFormat": "Network Transmit"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval])) * -1",
       "legendFormat": "Network Receive"
      }
     ]
    },
    {
     "title": "Subtitle Totals",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16547 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bazarr_queue_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "bazarr_history_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "bazarr_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "bazarr_subtitles_monitored_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Monitored"
      },
      {
       "expr": "bazarr_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Unmonitored"
      },
      {
       "expr": "bazarr_subtitles_missing_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "bazarr_subtitles_wanted_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "Wanted"
      }
     ]
    },
    {
     "title": "Episode Subtitles",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16551 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(bazarr_episode_subtitles_monitored_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(bazarr_episode_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "max(bazarr_episode_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Unmonitored"
      },
      {
       "expr": "max(bazarr_episode_subtitles_wanted_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Wanted"
      }
     ]
    },
    {
     "title": "Movie Subtitles",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16551 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(bazarr_movie_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "max(bazarr_movie_subtitles_monitored_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Monitored"
      },
      {
       "expr": "max(bazarr_movie_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Unmonitored"
      },
      {
       "expr": "max(bazarr_movie_subtitles_wanted_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Wanted"
      },
      {
       "expr": "max(bazarr_movie_subtitles_missing_total{instance=~\"${bazarr_instance}\"})",
       "legendFormat": "Missing"
      }
     ]
    },
    {
     "title": "Lifetime Downloads By Server",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16555 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Recent Downloaded By Server",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16555 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(increase(sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Recent Download Percent",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16555 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(increase(sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Scores",
     "type": "barchart",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 16564 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "bazarr_subtitles_score_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "{{score}}"
      }
     ]
    },
    {
     "title": "Providers",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16564 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bazarr_subtitles_provider_total{instance=~\"${bazarr_instance}\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Readarr - ${readarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "readarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 91803 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_system_status{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 91803 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"readarr\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 91803 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_author_downloaded_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Downloaded"
      },
      {
       "expr": "readarr_author_monitored_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Monitored"
      },
      {
       "expr": "readarr_author_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Authors Wanted"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 91803 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "readarr_queue_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "readarr_book_downloaded_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Downloaded"
      },
      {
       "expr": "readarr_history_total{instance=~\"${readarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "readarr_author_filesize_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Disk Used"
      },
      {
       "expr": "readarr_rootfolder_freespace_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Disk Free"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 91807 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"readarr.*\"}[$__rate_interval]))",
       "legendFormat": "Network Transmit"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"readarr.*\"}[$__rate_interval])) * -1",
       "legendFormat": "Network Receive"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 91807 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "readarr_author_filesize_bytes{instance=~\"${readarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 91807 },
     "targets": [
      {
       "expr": "readarr_system_health_issues{instance=~\"${readarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}