services:
  dozzle:
    image: amir20/dozzle:v8.7.0
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
    ports:
      - ${DOZZLE_PORT}

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${UPTIME_KUMA_DATA}:/app/data
    ports:
     - ${UPTIME_KUMA_PORT}
  
  postgresql:
    image: postgres:17.0
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}
      
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.1
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - ${NPM_DATA}:/data
      - ${NPM_LETS_ENCRYPT}:/etc/letsencrypt
    ports:
      - ${NPM_PORT_HTTP}
      - ${NPM_PORT_HTTPS}
      - ${NPM_PORT_ADMIN}
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - ${CADVISOR_PORT}

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    user: "root"
    volumes:
      - ${PROMTEHEUS_DATA}:/prometheus
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMTEHEUS_PORT}

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: unless-stopped
    user: "root"
    environment:  
      GF_SECURITY_ADMIN_USER: ${GRAFANA_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: ${GRAFANA_SECURITY_DISABLE_INITIAL_ADMIN_CREATION}
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GRAFANA_AUTH_ANONYMOUS_ORG_ROLE}
      GF_AUTH_DISABLE_SIGNOUT_MENU: ${GRAFANA_AUTH_DISABLE_SIGNOUT_MENU}
      GF_AUTH_DISABLE_LOGIN_FORM: ${GRAFANA_AUTH_DISABLE_LOGIN_FORM}
    ports:
     - ${GRAFANA_PORT}
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana

  exportarr-sonarr:
    image: ghcr.io/onedr0p/exportarr:v2.0.1

    container_name: exportarr-sonarr
    restart: unless-stopped
    environment:
      API_KEY: ${SONARR_EXPORTARR_API_KEY}
      PORT: ${SONARR_EXPORTARR_PORT}
      URL: ${SONARR_EXPORTARR_URL}
      ENABLE_ADDITIONAL_METRICS: ${SONARR_ENABLE_ADDITIONAL_METRICS}
      ENABLE_UNKNOWN_QUEUE_ITEMS: ${SONARR_ENABLE_UNKNOWN_QUEUE_ITEMS}
    ports:
      - ${SONARR_EXPORTARR_PORT}:${SONARR_EXPORTARR_PORT}
    command: ["sonarr"]

  exportarr-radarr:
    image: ghcr.io/onedr0p/exportarr:v2.0.1

    container_name: exportarr-radarr
    restart: unless-stopped
    environment:
      API_KEY: ${RADARR_EXPORTARR_API_KEY}
      PORT: ${RADARR_EXPORTARR_PORT}
      URL: ${RADARR_EXPORTARR_URL}
      ENABLE_ADDITIONAL_METRICS: ${RADARR_ENABLE_ADDITIONAL_METRICS}
      ENABLE_UNKNOWN_QUEUE_ITEMS: ${RADARR_ENABLE_UNKNOWN_QUEUE_ITEMS}
    ports:
      - ${RADARR_EXPORTARR_PORT}:${RADARR_EXPORTARR_PORT}
    command: ["radarr"]

  exportarr-lidarr:
    image: ghcr.io/onedr0p/exportarr:v2.0.1

    container_name: exportarr-lidarr
    restart: unless-stopped
    environment:
      API_KEY: ${LIDARR_EXPORTARR_API_KEY}
      PORT: ${LIDARR_EXPORTARR_PORT}
      URL: ${LIDARR_EXPORTARR_URL}
      ENABLE_ADDITIONAL_METRICS: ${LIDARR_ENABLE_ADDITIONAL_METRICS}
      ENABLE_UNKNOWN_QUEUE_ITEMS: ${LIDARR_ENABLE_UNKNOWN_QUEUE_ITEMS}
    ports:
      - ${LIDARR_EXPORTARR_PORT}:${LIDARR_EXPORTARR_PORT}
    command: ["lidarr"]

  exportarr-prowlarr:
    image: ghcr.io/onedr0p/exportarr:v2.0.1

    container_name: exportarr-prowlarr
    restart: unless-stopped
    environment:
      API_KEY: ${PROWLARR_EXPORTARR_API_KEY}
      PORT: ${PROWLARR_EXPORTARR_PORT}
      URL: ${PROWLARR_EXPORTARR_URL}
      ENABLE_ADDITIONAL_METRICS: ${PROWLARR_ENABLE_ADDITIONAL_METRICS}
      ENABLE_UNKNOWN_QUEUE_ITEMS: ${PROWLARR_ENABLE_UNKNOWN_QUEUE_ITEMS}
      PROWLARR__BACKFILL: ${PROWLARR__BACKFILL}
      PROWLARR__BACKFILL_DATE_SINCE: ${PROWLARR__BACKFILL_DATE_SINCE}
    ports:
      - ${PROWLARR_EXPORTARR_PORT}:${PROWLARR_EXPORTARR_PORT}
    command: ["prowlarr"]

  # bazarr-exportarr:
  #   image: ghcr.io/onedr0p/exportarr:v2.0.1

  #   container_name: bazarr-exportarr
  #   command: ["bazarr"]
  #   environment:
  #     PORT: 9712
  #     URL: "http://x.x.x.x:6767" # or; http://bazarr:6767
  #     APIKEY: "xxx"
  #   ports:
  #     - "9712:9712"
  #   restart: unless-stopped

  # readarr-exportarr:
  #   image: ghcr.io/onedr0p/exportarr:v2.0.1

  #   container_name: readarr-exportarr
  #   command: ["readarr"]
  #   environment:
  #     PORT: 9713
  #     URL: "http://x.x.x.x:8787" # or; http://readarr:8787
  #     APIKEY: "xxx"
  #   ports:
  #     - "9713:9713"
  #   restart: unless-stopped