---
- name: Copy prometheus.yaml to the ansible user's home
  copy:
    src: "{{ lookup('env', 'PROMETHEUS_CONFIG') }}"
    dest: /home/{{ ansible_user }}/prometheus.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'