---
talosVersion: v1.8.3
kubernetesVersion: v1.30.0

clusterName: talos-proxmox
endpoint: https://192.168.1.200:6443
additionalApiServerCertSans:
  - 192.168.1.199
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.1.199
  - 127.0.0.1
nodes:
  - hostname: talos-cp-0
    controlPlane: true
    ipAddress: 192.168.1.200
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:00"
        dhcp: true
        vip:
          ip: 192.168.1.199

  - hostname: talos-cp-1
    controlPlane: true
    ipAddress: 192.168.1.201
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:01"
        dhcp: true
        vip:
          ip: 192.168.1.199

  - hostname: talos-cp-2
    controlPlane: true
    ipAddress: 192.168.1.202
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:02"
        dhcp: true
        vip:
          ip: 192.168.1.199

  - hostname: talos-wk-0
    controlPlane: false
    ipAddress: 192.168.1.203
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:03"
        dhcp: true

  - hostname: talos-wk-1
    controlPlane: false
    ipAddress: 192.168.1.204
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:04"
        dhcp: true

  - hostname: talos-wk-2
    controlPlane: false
    ipAddress: 192.168.1.205
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:05"
        dhcp: true

  - hostname: talos-wk-3
    controlPlane: false
    ipAddress: 192.168.1.206
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0a:00:00:00:12:06"
        dhcp: true

controlPlane:
  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - "10.0.30.0/24"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles: ["os:admin"]
            allowedKubernetesNamespaces: ["system-upgrade"]