---
- name: Add user to sudo group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "sudo"
    append: yes

- name: Check if SSH port is reachable on the target host using nc (netcat)
  command: nc -zv {{ ansible_host }} 22
  register: nc_result
  retries: 16
  delay: 20
  until: nc_result.rc == 0
  ignore_errors: true
  tags: check_ssh

- name: Install necessary packages
  apt:
    name:
      - nfs-common
      - zip
      - net-tools
      - ca-certificates
      - curl
      - postgresql-client
      - git
    state: present
    update_cache: yes
  when: nc_result is succeeded
  