---
# - import_tasks: ../apt_lock_check/tasks/main.yaml

- name: Run VM initialization role
  include_role:
    name: ../../role/apt_lock_check

- block:
    - name: Add user to sudo group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "sudo"
        append: yes

    - name: Install necessary packages
      apt:
        name:
          - nfs-common
          - zip
          - net-tools
          - ca-certificates
          - curl
          - postgresql-client
          - git
        state: present
        update_cache: yes
  when: apt_lock_check_success
  name: "Add user and install packages only after apt lock is cleared"
