---
- name: Init Docker
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  roles:
    - /mnt/workspace/source/ansible/roles/vm_init
    - /mnt/workspace/source/ansible/roles/docker_install
    - /mnt/workspace/source/ansible/roles/docker_compose_down
    - /mnt/workspace/source/ansible/roles/docker_compose_up