---
# collector_init.
- name: Initialize Collectors
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load configuration
      include_role:
        name: role/config_load

    - name: Ping VM
      include_role:
        name: role/vm_ping

    - name: Initialize Prometheus
      block:
        - name: Migrate Prometheus configuration
          include_role:
            name: role/prometheus
        
        - name: Restart Docker Compose Managed Services
          include_role:
            name: role/docker_compose
          vars:
            run_down: true
            run_up: true
            up_services: "prometheus cadvisor exportarr-sonarr"
            down_services: "prometheus cadvisor exportarr-sonarr"
      when: vm_ping == true
