---
# docker_init
- name: Add Docker Hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Configuration
      include_role:
        name: role/load_config

    - name: Add docker hosts from config
      add_host:
        name: "{{ item.ansible_host }}:{{ item.ansible_port }}"
        ansible_host: "{{ item.ansible_host }}"
        ansible_port: "{{ item.ansible_port }}"
        groups: docker_hosts
      loop: "{{ config.ansible.host.docker }}"

- name: Initialize Docker Environment
  hosts: docker_hosts
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load Configuration
      hosts: localhost
      gather_facts: no
      tasks:
        - name: Load configuration
          include_role:
            name: role/load_config

    - name: Ping VM
      include_role:
        name: role/vm_ping

    - name: Docker Setup and Service Management
      block:
        - name: VM Initialization Tasks
          include_role:
            name: role/vm_init

        - name: Migrate Prometheus configuration
          include_role:
            name: role/prometheus

        - name: Install or Update Docker
          include_role:
            name: role/docker
      when: vm_ping == true
