---
# docker_init.
- name: Initialize Docker Environment
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load configuration
      include_role:
        name: role/load_config

    - name: Ping VM
      include_role:
        name: role/vm_ping

    - name: Docker Setup and Service Management
      block:
        - name: VM Initialization Tasks
          include_role:
            name: role/vm_init

        - name: Migrate Prometheus configuration
          include_role:
            name: role/prometheus

        - name: Install or Update Docker
          include_role:
            name: role/docker
      when: vm_ping == true
