---
version: "1"
module_version: 0.0.59
runner_image: spacelift/runner:latest
# tests:
#   - name: Test VM
#     terraform_version: 1.5.7
#     environment:
#       TF_VAR_CONFIG_PATH: /mnt/workspace/config.yaml
#       TF_VAR_node_name: pve