---
- name: Ensure node_exporter user exists
  ansible.builtin.user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: yes

- name: Determine the latest version of node_exporter
  ansible.builtin.uri:
    url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
    return_content: yes
  register: node_exporter_release

- name: Set node_exporter version
  set_fact:
    node_exporter_version: "{{ node_exporter_release.json.tag_name }}"

- name: Download node_exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version | regex_replace('^v', '') }}/node_exporter-{{ node_exporter_version | regex_replace('^v', '') }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/node_exporter

- name: Set ownership and permissions for node_exporter
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Create systemd service for node_exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: Restart node_exporter

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure node_exporter is enabled and running
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
