---
# debug_ansible.
- name: Add Docker Hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../../role/config/load

    - name: Add Host from Config
      include_role:
        name: ../../role/config/add_host
      vars:
        key: docker

- name: Debug
  hosts: docker
  gather_facts: no
  become: true
  check_mode: no
  tasks:
    - name: Load Configuration
      include_role:
        name: ../../role/config/load

    - name: Ping VM
      include_role:
        name: ../../role/virtual_machine/ping

    - name: Docker Setup and Service Management
      block:
        - name: Init VM
          include_role:
            name: ../../role/virtual_machine/init

      when: virtual_machine_ping == true
