---
- name: Verify SSH Port Accessibility via Netcat 
  command: nc -zv {{ ansible_host }} {{ ansible_port }} 
  register: nc_result 
  retries: 30 
  delay: 10 
  until: nc_result.rc == 0 
  ignore_errors: true 
  delegate_to: localhost
  become: false
  tags: check_ssh

- name: Define SSH Connectivity Status as a Fact
  set_fact:
    virtual_machine_ping: "{{ nc_result.rc == 0 }}"
