name: Create Spacelift Module Versions
on:
  workflow_dispatch:
    inputs:
      SPACELIFT_API_KEY_ENDPOINT:
        description: "Spacelift API Key Endpoint"
        required: true
      SPACELIFT_API_GITHUB_TOKEN:
        description: "Spacelift GitHub Token"
        required: true

jobs:
  spacectl:
    runs-on: ubuntu-latest
    environment: spacelift
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ github.event.inputs.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_GITHUB_TOKEN: ${{ github.event.inputs.SPACELIFT_API_GITHUB_TOKEN }}
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main

      - name: terraform-spacelift-stack
        run: |
          export MODULE="terraform-spacelift-stack"
          if ! spacectl module create-version --id $MODULE; then
            echo "Error encountered while creating version for module $MODULE. Ignoring and continuing."
          fi
