name: Create Spacelift Module Versions
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/create_spacelift_module_versions.yml"

jobs:
  create-module-versions:
    runs-on: ubuntu-latest
    environment: spacelift
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_GITHUB_TOKEN: ${{ secrets.SPACELIFT_API_GITHUB_TOKEN }}
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main

      - name: terraform-spacelift-stack
        run: |
          export MODULE="terraform-spacelift-stack"
          if ! spacectl module create-version --id $MODULE; then
            echo "Error encountered while creating version for module $MODULE. Ignoring and continuing."
          fi
