name: Packer Build - Base

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'packer/base.pkr.hcl'  # Automatically trigger when base.pkr.hcl is updated

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y qemu-system xorriso

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        if: startsWith(github.ref, 'refs/heads/')
        run: packer build .

      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build .

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/base.pkr.hcl"

      - name: Build Artifact
        run: packer build -color=false -on-error=abort ./packer/base.pkr.hcl
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
          HCP_BUCKET_NAME: "cloud-image"
          HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"
