name: Packer Build - Base

on:
  workflow_dispatch:
  push:
    paths:
      - 'packer/base.pkr.hcl'  # Automatically trigger when base.pkr.hcl is updated

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Install QEMU Plugin for Packer
        run: |
          mkdir -p ~/.config/packer/plugins/hashicorp.com/qemu/packer-plugin-qemu
          cd ~/.config/packer/plugins/hashicorp.com/qemu/packer-plugin-qemu
          curl -L -o packer-plugin-qemu.zip https://releases.hashicorp.com/packer-plugin-qemu/1.0.0/packer-plugin-qemu_1.0.0_linux_amd64.zip
          unzip packer-plugin-qemu.zip
          rm packer-plugin-qemu.zip

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/base.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/base.pkr.hcl"

      - name: Build Artifact
        run: packer build -color=false -on-error=abort ./packer/base.pkr.hcl
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"
