name: Init Spacelift Modules
on:
  workflow_dispatch:
jobs:
  spacectl:
    runs-on: ubuntu-latest
    environment: spacelift
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_GITHUB_TOKEN: ${{ secrets.SPACELIFT_API_GITHUB_TOKEN }}
    steps:
      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main

      - name: Check and conditionally create version
        run: |
          # Run spacectl module list and parse output for the Current Version field of the target module
          echo spacectl module list
          version=$(spacectl module list | grep -w "terraform-spacelift-stack" | awk '{print $3}')
          echo "Current version found: '$version'"  # Debugging output
          # Set a default value if version is empty
          if [ -z "$version" ]; then
            echo "No version found. Creating a new version."
            spacectl module create-version --id terraform-spacelift-stack
          else
            echo "Version already exists: $version. Skipping creation."
          fi
